swagger: '2.0'
info:
  title: Gestion des Transactions API
  version: '1.0.0'

paths:
  /transactions:
    get:
      summary: Récupérer toutes les transactions du mois en cours, groupées par compte
      parameters:
        - name: month
          in: query
          description: Mois pour lequel récupérer les transactions (format YYYY-MM)
          required: true
          type: string
        - name: accountId
          in: query
          description: ID du compte (si spécifié, les transactions sont filtrées par compte)
          required: false
          type: integer
      responses:
        200:
          description: Succès. Renvoie la liste des transactions.
        400:
          description: Mauvaise requête. Les paramètres de la requête sont invalides.
        404:
          description: Aucune transaction trouvée pour les critères spécifiés.

    post:
      summary: Ajouter une nouvelle transaction
      parameters:
        - name: transactionData
          in: body
          description: Données de la nouvelle transaction
          required: true
          schema:
            type: object
            properties:
              accountId:
                type: integer
                description: ID du compte lié à la transaction
              amount:
                type: number
                description: Montant de la transaction
              description:
                type: string
                description: Description de la transaction
      responses:
        201:
          description: Créé avec succès. Renvoie les détails de la nouvelle transaction.
        400:
          description: Mauvaise requête. Les données de la transaction sont invalides.

  /transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à récupérer
          required: true
          type: integer
      responses:
        200:
          description: Succès. Renvoie les détails de la transaction spécifiée.
        404:
          description: La transaction spécifiée n'a pas été trouvée.

    put:
      summary: Mettre à jour les informations d'une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à mettre à jour
          required: true
          type: integer
        - name: updatedData
          in: body
          description: Données mises à jour de la transaction
          required: true
          schema:
            type: object
            properties:
              amount:
                type: number
                description: Nouveau montant de la transaction
              description:
                type: string
                description: Nouvelle description de la transaction
      responses:
        200:
          description: Succès. Renvoie les détails de la transaction mise à jour.
        400:
          description: Mauvaise requête. Les données de mise à jour de la transaction sont invalides.
        404:
          description: La transaction spécifiée n'a pas été trouvée.

    delete:
      summary: Supprimer une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à supprimer
          required: true
          type: integer
      responses:
        204:
          description: Supprimé avec succès.
        404:
          description: La transaction spécifiée n'a pas été trouvée.
